language: r

env:
  global:
    - PKG_CXXFLAGS="-pedantic"

# Be strict when checking our package
warnings_are_errors: true
cran: http://cran.us.r-project.org

# System dependencies for HTTP calling
apt_packages:
 - libhdf5-serial-dev libhdf5-dev libhdf5-7
