language: r

env:
  global:
    - PKG_CXXFLAGS="-pedantic"
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"

# Be strict when checking our package
warnings_are_errors: true
cran: http://cran.us.r-project.org

# System dependencies for HTTP calling
apt_packages:
 - libhdf5-serial-dev libhdf5-dev libhdf5-7
r_github_packages:
  - jimhester/covr
  - hadley/staticdocs
after_success:
  - R --slave --vanilla -e 'library(covr); pc <- package_coverage(); pc; codecov(coverage = pc)'
before_deploy: 
  - R -e "staticdocs::build_site(examples = TRUE)" 
  
#deploy: 
#  edge: true
#   
#  provider: s3 
#  access_key_id: AKIAJDM6KGIZ6LSGAK4Q 
#  secret_access_key: 
#    secure: "r3vSpvVNcpvIcjWFyk+GhYG55iuhfmy3mwuQHQS2EqjT3Skd3mOojnZuRIqy60XXElK5/nfa3qt7KH0GCSd4Is28cqPwh+1PtQ0ZVXfeKefAk2whTPDI4P+rgOA+srUxZraLALap9QGmvlzJyXbqBCRdDmXUjtXKi2ONE9PrUk4=" 
#  bucket: docs.ggplot2.org 
#  skip_cleanup: true 
#  local-dir: inst/web 
#  upload-dir: dev 
  